name: Release and Deploy Build

on:
    workflow_dispatch:

permissions:
    contents: write

env:
    VERSION_MAJOR: '1'
    VERSION_MINOR: '1'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Use NodeJS v22.22.3
              uses: actions/setup-node@v6
              with:
                  node-version: '22.22.3'
                  registry-url: 'https://registry.npmjs.org'
                  package-manager-cache: false

            - name: Install Dependencies
              run: npm ci

            - name: Set Release Version
              id: version
              run: npm run release:version

            - name: Export Release Version
              id: release_version
              run: |
                  package_version="$(node -p "require('./package.json').version")"
                  echo "tag=${package_version}" >> "$GITHUB_OUTPUT"

            - name: Run Build
              run: npm run build
